# Generated by Django 5.2.4 on 2025-07-08 17:57

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to=app.models.file_name_set, validators=[app.models.validate_pdf])),
            ],
        ),
    ]
